/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.jgrapht.Graph;
import org.jgrapht.graph.DefaultEdge;
import org.jgrapht.graph.SimpleGraph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // Create a simple graph with JGraphT
        Graph<String, DefaultEdge> graph = new SimpleGraph<>(DefaultEdge.class);

        // Add some vertices
        graph.addVertex("A");
        graph.addVertex("B");
        graph.addVertex("C");

        // Add some edges
        graph.addEdge("A", "B");
        graph.addEdge("B", "C");
        graph.addEdge("C", "A");

        // Print the graph
        System.out.println("Graph: " + graph.toString());
    }
}